- cmd/dracon/cmd/root.go
- cmd/dracon/cmd/run.go
- cmd/dracon/cmd/setup.go
- docs/getting-started/minikube.md
- pkg/kubernetes/BUILD
- pkg/kubernetes/apply.go
- pkg/kubernetes/apply_test.go
This diff adds support for the `--context` and `--namespace` kubectl flags to dracon.
> support context and namespace kubectl flags

- pkg/kubernetes/BUILD
- pkg/kubernetes/apply.go
- pkg/putil/BUILD
- pkg/putil/write.go
This diff adds:
- the use of go 1.13 errors everywhere
- the cmd output error message returned from when `kubectl apply` fails
> go 1.13 errors everywhere and error message from kubectl

- consumers/elasticsearch_c/BUILD
- consumers/elasticsearch_c/main.go
- resources/persistence/elasticsearch-kibana/elasticsearch.yaml
- resources/persistence/elasticsearch-kibana/kibana.yaml
- third_party/go/BUILD
This PR upgrades our elasticsearch consumer to only support ES version 7 (the latest).
> upgrade to ES 7

- .plzconfig
- third_party/proto/BUILD
This PR introduces support for protoc.
In addition, we no longer require a user to have protoc within his/her toolchain.
> Add protoc support

- third_party/python/BUILD
Have updated the third party hashes for two reasons. 1) It looks like they were updated on the server but without bumping version numbers (perhaps to regenerate the whl's files). 2) Defectdojo does not have a pre-build whl leading to deterministic builds and the hashes failing. Going forward it may be necessary to keep updating some third party hashes, if they were unfortunately regenerated on the server side.
> Fix hashes

- scripts/publish-images.sh
The publish images script gets confused due to binary metadata being produced by plz. This change modifies that script to skip any metadata files before publishing the images.
> Update the publish image script to skip the metadata

- scripts/dev-images.sh
- scripts/publish-images.sh
Recent versions of Please output `.target_*` files, which causes problems for `dev-images.sh` and `publish-images.sh` when they search for files whose names end with `_fqn`. Omit the `.target_*` files from the searches these files perform.
Credit to @northdpole for figuring out what was causing `dev-images.sh` to fail with the latest version of Please 🙂
> scripts/*-images.sh: omit .target_* files from searches

- pkg/enrichment/db/BUILD
- pkg/enrichment/db/db.go
When the enricher connects to the database, check for the existence of a schema search path (`search_path`) in the connection string and perform the following actions if one is found:
* create a schema with the name given by the value of `search_path` if it doesn't already exist;
* configure the migrations instance to use the schema with the name given by the value of `search_path`.
This allows for the easy partitioning of enrichment data for different pipelines.
> Enricher: add database schema support

- producers/golang_gosec/main.go
- producers/golang_gosec/main_test.go
This quick fix regards issue #49. Gosec producer's `Title` and `Description` fields should be swapped around (see info in #49)
> Fix Gosec producer's Title and Description fields

- source/git/Dockerfile
To facilitate fetching the remote codebase via `git archive`, add GNU Tar to the Git source container (BusyBox's `tar` implementation has an insufficiently powerful `--exclude` option).
> Add GNU Tar to Git source container

- producers/typescript_tslint/BUILD
- producers/typescript_tslint/Dockerfile
- producers/typescript_tslint/main.go
- producers/typescript_tslint/main_test.go
- producers/typescript_tslint/types/BUILD
- producers/typescript_tslint/types/tslint-issue.go
[TSLint](https://palantir.github.io/tslint/usage/cli/) has a [security rules plugin ](https://github.com/webschik/tslint-config-security). In order to allow dracon to scan Typescript files it makes sense to integrate a tslint parser.
This pull request does so
> TSLint Producer, for the security rules

- .plzconfig
This PR pins the please.build version to v15.5.0 as the most recent build (v15.6.0) breaks our Go builds.
> Pin please to v15.5.0

- .github/workflows/publish.yml
- docs/contributers/RELEASES.md
- scripts/pre-release.sh
This PR adds the `./pleasew run //scripts:publish-images` to the `release` workflow so that Docker images are automatically pushed via CI/CD for each release. I have added the following secrets to the repository's actions for this to work:
- `DOCKERHUB_USERNAME`: `vjftw` (my Docker Hub account).
- `DOCKERHUB_PASSWORD`: A unique secret access token only used for this repository's GitHub Actions. (https://docs.docker.com/docker-hub/access-tokens/)
From the "Secrets" page in "Settings" for this repository:
> Secrets are environment variables that are encrypted and only exposed to selected actions. Anyone with collaborator access to this repository can use these secrets in a workflow.
> Secrets are not passed to workflows that are triggered by a pull request from a fork.
> Automatically push docker images during release CI/CD

- producers/golang_gosec/Dockerfile
gosec supports a configuration file, but the range of settings that can be configured within it is limited; in particular, it lacks equivalents for the `-include`, `-exclude` and `-exclude-dir` command line options. Add jq to the gosec producer container, so that values for these options can be specified in the configuration file and transformed into real command line options by the Dracon producer.
> Add jq to gosec producer container

- producers/golang_gosec/Dockerfile
gosec itself doesn't run in this container, so there's no use in jq being available in this container after all (since the intended purpose of it was to extract fields from gosec's JSON-based configuration file and transform them into gosec command line options).
This reverts commit 10d7faf536fda6d47e26bc4cb41d1997a0d39715.
> Revert "Add jq to gosec producer container (#61)"

- .github/workflows/publish.yml
- docs/contributers/RELEASES.md
- scripts/tag-release.sh
This PR:
* adds a script to help make releases a lot easier to perform (run a script and follow the instructions).
* it also removes the creation of releases on every push to master as they can get quite noisy very quickly.
> Make releasing friendlier and less noisy

- build/docker/Dockerfile-base-go
unbork alpine containers. Since we started building with github actions, the /produce and /consume binaries couldn't be ran because we build against glibc and we run in alpine which uses musl. The easiest fix is to add the glibc compatibility layer in our base golang container.
> unbork alpine containers

- pkg/enrichment/BUILD
- pkg/enrichment/db/BUILD
- pkg/enrichment/issue.go
- pkg/enrichment/issue_test.go
The enricher so far was assuming that an issue found across 2 different commits counts as a regression (was taking into account the source git repo reference when calculating finding unique hashes)
Since 1 commit is unrealistically short period for orgs with a monorepo, this pr drops the ?ref=<val> part of the "source" field when it calculates the hash.
WARNING: this means that Dracon currently cannot process regressions, once it finds something on a repository it will always be marked as a duplicate, fgurther work is needed to address this
> dropped the ref check from the enricher

- pkg/enrichment/db/BUILD
- pkg/enrichment/db/db.go
- pkg/enrichment/db/issue.go
- third_party/go/BUILD
- third_party/subrepos/BUILD
depends on https://github.com/thought-machine/dracon/pull/68
makes enrichment db mockable, adds delete capability into the db object
> Enrichment changes

- pkg/putil/write.go
- producers/producer.go
- producers/producer_test.go
To support incremental writing of producer output files, add support for an `-append` option to the common producer library. When specified on the command line, this appends issues from the file given by `-in` to the list of issues in the protobuf stored in `-out` if `-out` already exists and is non-empty, rather than overwriting the existing file entirely.
> Add -append option to producers

- producers/elasticsearch_filebeat/BUILD
- producers/elasticsearch_filebeat/Dockerfile
- producers/elasticsearch_filebeat/main.go
- producers/elasticsearch_filebeat/main_test.go
- producers/elasticsearch_filebeat/types/BUILD
- producers/elasticsearch_filebeat/types/elasticsearch-filebeat-issue.go
Tested with:
```
plz build //producers/elasticsearch_filebeat:elasticsearch_filebeat
plz test //producers/elasticsearch_filebeat:elasticsearch_filebeat_test
plz build //producers/elasticsearch_filebeat:dracon-producer-elasticsearchfilebeat
plz-out/bin/producers/elasticsearch_filebeat/dracon-producer-elasticsearchfilebeat.sh
cd /tmp
docker run -v $(pwd):/code/ --rm -it thoughtmachine/dracon-producer-elasticsearch-filebeat -in /code/elastic-out.json -out /code/dracon-out.pb 
```
> Add elasticsearch_filebeat producer

- scripts/tag-release.sh
`git tag | sort` can't reliably identify the tag with the highest version number because it sorts lexicographically, so (for example) v1.10.0 is considered less recent than v0.9.0. Instead, use `git tag`'s built-in logic for sorting tags.
Closes #82.
> tag-release.sh: use Git's built-in logic to sort tags

- common/jira/config.yaml
- common/jira/jira/apiutils.go
- common/jira/jira/apiutils_test.go
we had a bug were the jira consumer would fail with "Operation value must be a string" when updating a specific customfield. Turns out jira supports two types of single value fields
```
"customfield_15801" :
{"value" : "Test"}
}
```
and 
` "customfield_15801": "TEST"`
source:
https://community.atlassian.com/t5/Jira-questions/JIRA-REST-API-calls-failing-with-quot-Operation-value-must-be-a/qaq-p/755656
updating the jira consumer to recognise this use case
> support direct value jira fields

- producers/mobsf/report/android/android_test.go
- producers/mobsf/report/ios/ios_test.go
Avoid non-deterministic failures in the MobSF producer tests by sorting issues slices before comparing them with the list of expected issues - the order doesn't actually matter for the purposes of these tests, just the contents of the slices.
> Stabilise order of issues slices in MobSF producer tests

- docs/contributers/RELEASES.md
The release instructions are much simpler than pushing our own tags etc. So i've removed the explanation. We could probably re-add this in a much less prominent place if we wanted to explain it in the future.
> Remove confusing release instructions

- scripts/development/k8s/tektoncd-dashboard/BUILD
- scripts/development/k8s/tektoncd-dashboard/ingress.yaml
- scripts/development/k8s/tektoncd-dashboard/kustomization.yaml
- scripts/development/kind/BUILD
- scripts/development/kind/configuration.yaml
- scripts/development/kind/setup.sh
- third_party/k8s/BUILD
This PR:
* Updates Tekton Pipelines to v0.22.0 (and K8s to 1.17 to support this)
* Adds Tekton Dashboard available at https://dashboard.localhost
> Update Tekton and add Tekton Dashboard

- .plzconfig
- consumers/elasticsearch_c/main.go
- pkg/enrichment/db/db.go
- third_party/go/BUILD
- third_party/lang/BUILD
This PR:
* Updates to Golang 1.16
* Uses the new (and better) `go_module` rule for managing Go modules
> Update to Golang 1.16

- .github/workflows/e2e.yml
- scripts/development/kind/configuration.yaml
- scripts/development/kind/setup.sh
- third_party/k8s/BUILD
This PR:
* Adds a GitHub Actions matrix to ensure we support our E2E running of Dracon against multiple Kubernetes versions
* Downgrades TektonCD pipelines to versions which support K8s 1.16 until we remove support for K8s 1.16.
* Adds verification hashes for k8s remote files
> Add support for E2E against multiple k8s versions

- third_party/go/BUILD
- third_party/lang/BUILD
- third_party/proto/BUILD
- third_party/python/BUILD
This will cause a build failure if any of the upstream dependencies change, which means we can investigate what happened
> Ensure third party dependencies have hashes

- producers/zap_producer/BUILD
- producers/zap_producer/Dockerfile
- producers/zap_producer/main.go
- producers/zap_producer/main_test.go
- producers/zap_producer/types/BUILD
- producers/zap_producer/types/zap-issue.go
Support ZAP as a Dracon producer. 
Currently, it parses the results of a ZAP scan JSON output.
Please note: The issue description will contain the description of the finding and additional information such as resolution and reference.
> Add ZAP producer

- common/jira/jira/api.go
- common/jira/jira/apiutils.go
- common/jira/jira/apiutils_test.go
jira summary field is capped at 255 characters, the jira consumer needs to truncate longer summaries and add the extra parts in the description
> truncate summary and add the extra to description

- producers/producer.go
- producers/yarn_audit/BUILD
- producers/yarn_audit/Dockerfile
- producers/yarn_audit/README.md
- producers/yarn_audit/main.go
- producers/yarn_audit/types/BUILD
- producers/yarn_audit/types/yarn-issue.go
- producers/yarn_audit/types/yarn-issue_test.go
- Add support for reading lines in producer.go
- Each json line if of the form `{"type": "....", "data": "...."}`, where the shape of the value for `data` is dependendent on value for `type`
- This adds a `YarnAuditReport` `struct` in `yarn-issues.go` that includes
- `AuditSummary` - the `data` field from the json line with `"type": "auditSummary"`
- `AuditActions` - the list of `data` fields from json lines with `"type": "auditAction"`
- `AuditAdvisories` - the list of `data` field from json lines with `"type": "auditAdvisory"`
- `AsIssues()` function that returns a the list of `v1.Issues` used by Dracon. This only uses the `AuditAdvisories` field of the report for now.
> Dracon producer to parse `yarn audit --json` jsonlines

- .github/workflows/e2e.yml
- scripts/development/kind/setup.sh
- third_party/k8s/BUILD
- third_party/tools/BUILD
This bumps the pipeline version to 0.34.1 and the dashboard version to 0.25.0. Unfortunately the latter does not support the latest pipeline version (0.35.0), which is why we are using the one before.
> Bump tekton version

- consumers/elasticsearch/BUILD
- consumers/elasticsearch/Dockerfile
- consumers/elasticsearch/main.go
- consumers/elasticsearch/main_test.go
- examples/pipelines/golang-project/BUILD
- examples/pipelines/golang-project/elasticsearch-consumer.yaml
- examples/pipelines/mixed-lang-project/BUILD
- examples/pipelines/mixed-lang-project/elasticsearch-consumer.yaml
- examples/pipelines/python-project/BUILD
- examples/pipelines/python-project/elasticsearch-consumer.yaml
- scripts/development/k8s/elasticsearch-kibana/elasticsearch.yaml
- scripts/development/k8s/elasticsearch-kibana/kibana.yaml
- third_party/go/BUILD
- Switch to supporting ESv8
- Remove code that pretends to support more than the single ES version
- Rename elasticsearch_c -> elasticsearch to tidy up the name
- Allow passing of ES cluster urls via flags (as well as existing env variable)
> Support Elasticsearch 8

- producers/yarn_audit/README.md
- producers/yarn_audit/main.go
- producers/yarn_audit/types/yarn-issue.go
- producers/yarn_audit/types/yarn-issue_test.go
The existing yarn-audit producer fails due to odd golang behaviour that mangles the contents of `[][]byte` structures. This is a rewrite of the yarn-audit producer to instead read input into a `[]byte` structure, similar to the npm-audit producer, which is not mangled in the same way.
This PR also:
- updates the README to reflect the necessary use of `jq` on `yarn audit` output to get a JSON array back
- updates the auditAdvisory struct to accept arrays of CWEs, as provided by `yarn audit`
- rewrites existing tests to fit the new structure
> Rewrite yarn-audit producer

- pkg/enrichment/db/issue.go
Entries in the enrichment DB added before the change to record CVEs have NULL values in the CVE column. This is not handled by the string type, resulting in errors trying to convert existing DB issues to enriched issues. This PR changes the CVE field in the DB issue struct to be sql.NullString, which does have handling for NULL values.
> Handle enrichment DB entries without CVEs

- .plzconfig
- third_party/go/BUILD
- third_party/lang/BUILD
On some OS architectures, k8s klog (dependency of apimachinery) causes a segfault. The root cause for this is unknown; it is possibly due to some unsafe race condition when calling os.User(). Updating apimachinery and its transitive dependencies (including x/sys/unix, and the go toolchain) fixes this segfault. Updating the Please version allows the unix library to be correctly linked.
> Update dependencies to fix segfault caused by k8s klog v1

- producers/yarn_audit/main.go
The enricher always expects producers that run before it to output results files, even if the producer found no issues to report. This isn't the case with the `yarn audit` producer - a results file is only written if at least one issue was found.
Write a results file regardless of how many issues were found by the producer.
Fixes #144.
> `yarn audit` producer: unconditionally write results file

- scripts/BUILD
- scripts/publish-images.sh
Push Docker images to both Docker Hub and the repo's container registry on GitHub - GHCR's rate limits are much more generous than Docker Hub's.
> Publish images to GitHub Container Registry

- pkg/template/load.go
- pkg/template/load_test.go
Small commit so that empty YAML documents in a multi-doc YAML file are handled properly (they are currently converted to `nil` elements in the list which could be handled improperly).
> Fix to handle empty YAML documents
